// -------- template Data - use for init ---------- //
// ------------------------------------------------ //
export const allRecruitData = [
    {
        displayId: 1,
        lightText: false,
        imgStart: true,
        jobTitle: 'Front-End Developer',
        location: 'Ha Noi',
        shortDescription: ['TypeScript', 'ReactJS', 'JavaScript'],
        salary: 'Upto 25M',
        // headline: 'FRONTEND-DEV --- Lead Generation specialist for Online Business',
        description: 'You will be responsible for building, maintaining the client-side of customer web applications. You should be able to translate our company and customer needs into functional applications. If you’re interested in creating a user-friendly environment this job is for you.',
        descriptionVN: 'Bạn sẽ chịu trách nhiệm xây dựng, chỉnh sửa, bảo trì những website ứng dụng cho khách hàng. Bạn sẽ có thể chuyển nhu cầu của công ty và khách hàng của chúng tôi thành các ứng dụng tương tác có chức năng và hấp dẫn. Nếu bạn quan tâm đến việc tạo ra một môi trường thân thiện với người dùng bằng cách viết mã và tiến lên trong sự nghiệp của mình thì công việc này là dành cho bạn.',
        experience: 'Have at least 6 months of major experience working with ReactJS. Deep understanding of basic React concepts, such as components, state, props, lifecycle, and hooks. Strong knowledge of JavaScript and ES6+. Skills in working with state management, experience using state management libraries such as Redux or Context API. Understanding of React Router, skills in using React Router to manage navigation in the application. Experience working with RESTful APIs. Understanding of responsive design, skills in working with CSS (styled-components).',
        experienceVN: 'Có ít nhất 6 tháng kinh nghiệm làm việc chính với ReactJS. Hiểu biết sâu sắc về các khái niệm cơ bản của React, như component, state, props, lifecycle, và hooks. Kiến thức vững về JavaScript và ES6+. Kỹ năng làm việc với state management, kinh nghiệm sử dụng các thư viện quản lý trạng thái như Redux hoặc Context API. Hiểu biết về React Router, kỹ năng sử dụng React Router để quản lý điều hướng trong ứng dụng. Kinh nghiệm làm việc với RESTful APIs. Hiểu biết về responsive design, kỹ năng làm việc với CSS (styled-components).',
        expPlus: 'Kinh nghiệm sử dụng TypeScript. Tối ưu hoá hiệu suất ứng dụng. Có khả năng đưa ra giải pháp giải quyết tốt vấn đề.',
        img: require('../../images/rec-frontend-dev.jpg'),
        url: "https://images.pexels.com/photos/57007/pexels-photo-57007.jpeg?auto=compress&cs=tinysrgb&w=1600",
        alt: 'Image',
        benefit: 'Thử việc hưởng 100% lương. Ký hợp đồng lao động chính thức sau 02 tháng thử việc. Nghỉ phép 12 ngày/năm, nghỉ Golden Week, Tết dương lịch theo lịch Nhật, nghỉ Tết âm lịch, kỷ niệm thành lập công ty. Du lịch hè cùng công ty hoặc nghỉ hè 3 ngày tự chọn. Làm việc: 9h-18h từ T2-T6, nghỉ T7 và CN hàng tuần, không tăng ca. Khám sức khoẻ định kỳ hàng năm, xét duyệt tăng lương định kỳ 1 năm/lần, thưởng 2 lần/năm (tháng lương thứ 13 và 14). Hỗ trợ thi chứng chỉ quốc tế. Chế độ BHXH, BHYT. Môi trường trẻ trung năng động, thoải mái, tạo điều kiện để cá nhân phát triển năng lực nhất có thể. Free trà, cà phê, chỗ gửi xe.',
    },
    {
        displayId: 2,
        lightText: false,
        imgStart: false,
        jobTitle: 'Back-End Developer',
        location: 'Tokyo',
        // headline: 'BACKEND-DEV --- Lead Generation specialist for Online Business', 
        shortDescription: ['Python', 'Flask', 'MySQL'],
        salary: 'Upto 25M',
        description: 'We are looking for candidates who are strong in Back-End development, at least 1 year experience working with Python. Our customers are people who have products with in-depth analysis and processing systems in the fields of construction, agriculture, transportation... it will be great if you are someone who likes to solve difficult problems. hammer, helping customers be satisfied with our solutions.',
        descriptionVN: 'Chúng tôi đang tìm kiếm ứng viên có thể mạnh trong phát triển Back-End đặc biệt là Python. Khách hàng của chúng tôi là những người có sản phẩm với hệ thống phân tích, xử lý chuyên sâu trong lĩnh vực xây dựng, nông nghiệp, giao thông...sẽ rất tuyệt vời nếu bạn là người thích giải quyết những bài toán hóc búa, giúp khách hàng hài lòng với những giải pháp của mình.',
        experience: 'Have experience working with popular frameworks such as Django (web development), Flask, FastAPI. Skills to work with database management systems such as MySQL, SQLAlchemy or SQLite. Understanding of SQL query language. Experience in API development and integration, understanding of protocols such as RESTful. Skills in working with libraries and frameworks such as NumPy, Pandas, OpenCV.',
        experienceVN: 'Đã có kinh nghiệm làm việc với các frameworks phổ biến như Django (web development), Flask, FastAPI. Kỹ năng làm việc với hệ quản trị cơ sở dữ liệu như MySQL, SQLAlchemy hoặc SQLite. Hiểu biết về ngôn ngữ truy vấn SQL. Kinh nghiệm phát triển và tích hợp API, hiểu biết về các giao thức như RESTful. Kỹ năng làm việc với thư viện và frameworks như NumPy, Pandas, OpenCV.',
        expPlus: 'Experience with performance optimization, data caching is a plus. Experience working with front-end frameworks like ReactJS.',
        expPlusVN: 'Có kinh nghiệm tối ưu hóa hiệu suất, bộ nhớ đệm dữ liệu là một lợi thế. Kinh nghiệm làm việc với front-end frameworks như ReactJS.',
        img: require('../../images/rec-backend-dev.jpg'),
        url: "https://images.pexels.com/photos/785418/pexels-photo-785418.jpeg?auto=compress&cs=tinysrgb&w=1600",
        alt: 'Image',
        benefit: 'Thử việc hưởng 100% lương. Ký hợp đồng lao động chính thức sau 02 tháng thử việc. Nghỉ phép 12 ngày/năm, nghỉ Golden Week, Tết dương lịch theo lịch Nhật, nghỉ Tết âm lịch, kỷ niệm thành lập công ty. Du lịch hè cùng công ty hoặc nghỉ hè 3 ngày tự chọn. Làm việc: 9h-18h từ T2-T6, nghỉ T7 và CN hàng tuần, không tăng ca. Khám sức khoẻ định kỳ hàng năm, xét duyệt tăng lương định kỳ 1 năm/lần, thưởng 2 lần/năm (tháng lương thứ 13 và 14). Hỗ trợ thi chứng chỉ quốc tế. Chế độ BHXH, BHYT. Môi trường trẻ trung năng động, thoải mái, tạo điều kiện để cá nhân phát triển năng lực nhất có thể. Free trà, cà phê, chỗ gửi xe.',
    },
    {
        displayId: 3,
        lightText: false,
        imgStart: true,
        jobTitle: 'Cloud Engineer',
        location: 'Japan',
        // headline: 'CLOUD --- Lead Generation specialist for Online Business', 
        shortDescription: ['AWS', 'Azure', 'Google CLoud'],
        salary: 'Upto 50M',
        description: 'We are looking for a passionate and meticulous Cloud Engineer to participate in important transformation work/projects. Here, you will have the opportunity to contribute to building and maintaining flexible, secure, scalable cloud systems, optimizing technical work to increase productivity.',
        descriptionVN: 'Chúng tôi đang tìm kiếm một Cloud Engineer đam mê và chỉn chu để tham gia vào những công việc/dự án chuyển đổi có tính chất quan trọng. Tại đây, bạn sẽ có cơ hội đóng góp vào việc xây dựng và duy trì hệ thống đám mây linh hoạt, an toàn, có khả năng mở rộng, tối ưu những công việc kỹ thuật giúp tăng năng suất.',
        experience: 'Understanding of services from popular cloud providers such as Amazon Web Services (AWS), Microsoft Azure, Google Cloud Platform (GCP), or others. At least 6 months of experience building, deploying, and managing systems in cloud environments. Use tools like Terraform, AWS CloudFormation, or Azure Resource Manager to automate infrastructure deployment and management. Strong knowledge of networking concepts such as VPCs, subnets, routing, and VPNs. Understanding of security measures and best practices in cloud environments. Use monitoring tools like Prometheus, Grafana, or AWS CloudWatch to monitor system performance and stability.',
        experienceVN: 'Hiểu biết về các dịch vụ của các nhà cung cấp đám mây phổ biến như Amazon Web Services (AWS), Microsoft Azure, Google Cloud Platform (GCP), hoặc các nhà cung cấp khác. Có ít nhất 6 tháng kinh nghiệm xây dựng, triển khai, và quản lý hệ thống trên các môi trường đám mây. Sử dụng các công cụ như Terraform, AWS CloudFormation, hoặc Azure Resource Manager để tự động hóa việc triển khai và quản lý hạ tầng. Kiến thức vững về các khái niệm networking như VPCs, subnets, routing, và VPNs. Hiểu biết về các biện pháp bảo mật và best practices trong môi trường đám mây. Sử dụng các công cụ giám sát như Prometheus, Grafana, hoặc AWS CloudWatch để theo dõi hiệu suất và tính ổn định của hệ thống.',
        expPlus: 'Understanding of one or more programming and scripting languages such as Python, Shell Scripting, or PowerShell. Understanding of Docker and principles of containerization. Experience using container management tools such as Kubernetes.',
        expPlusVN: 'Hiểu biết về một hoặc nhiều ngôn ngữ lập trình và scripting như Python, Shell Scripting, hoặc PowerShell. Hiểu biết về Docker và các nguyên lý của containerization. Kinh nghiệm sử dụng các công cụ quản lý container như Kubernetes.',
        img: require('../../images/rec-cloud-engineer.png'),
        url: "https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=1600",
        alt: 'Image',
        benefit: 'Thử việc hưởng 80% lương. Đào tạo nội bộ (nếu có) và ký hợp đồng lao động chính thức sau 06 tháng. Nghỉ phép 12 ngày/năm, Golden Week, Tết dương lịch, các ngày lễ theo lịch đỏ của Nhật, kỷ niệm thành lập công ty. Nghỉ hè 3 ngày tự chọn. Làm việc: 9h-18h từ T2-T6, nghỉ T7 và CN hàng tuần. Thưởng 2 lần/năm (tháng lương thứ 13 và 14). Hỗ trợ thi chứng chỉ quốc tế. Chế độ BHXH, BHYT. Hỗ trợ tiền tầu xe hàng tháng.',
    },
    {
        displayId: 4,
        lightText: false,
        imgStart: false,
        jobTitle: 'Devops Engineer',
        location: 'Ha Noi/Japan',
        // headline: 'DEVOPS --- Lead Generation specialist for Online Business',
        shortDescription: ['Docker', 'Kubernetes', 'Rancher'],
        salary: 'Negotiate',
        description: 'Participating in research, design, implementation and operation of Cloud-based systems (mainly AWS but also Azure or GCP). Implement CI/CD for the system. Build Cloud infrastructure as code (Terraform, AWS CloudFormation, ...). Fix problems and set up the environment on the Cloud.',
        descriptionVN: 'Tham gia nghiên cứu, thiết kế, triển khai và vận hành các hệ thống trên nền tảng Đám mây (chủ yếu là AWS có thể là cả Azure hoặc GCP). Triển khai CI/CD cho hệ thống. Xây dựng cơ sở hạ tầng Đám mây dưới dạng mã (Terraform, AWS CloudFormation, ...). Khắc phục sự cố và thiết lập môi trường trên đám mây.',
        experience: 'Deep understanding of DevOps-related technologies such as Docker, Kubernetes, Ansible, Terraform, Jenkins, and others. Proficient in at least one programming language, usually Python, Ruby, or Bash scripting. Strong knowledge of systems and networking to be able to effectively deploy and maintain the system. Experience using version control systems like Git and development workflows like GitFlow. Skills to set up and maintain automation processes using tools such as Ansible, Puppet, or Chef. Understanding of IaC and using tools like Terraform to manage infrastructure. Experience building and maintaining CI/CD pipelines to automate development and deployment processes. Understanding of system monitoring and logging to enable analysis and troubleshooting.',
        experienceVN: 'Hiểu biết sâu sắc về các công nghệ liên quan đến DevOps như Docker, Kubernetes, Ansible, Terraform, Jenkins, và các công cụ khác. Thành thạo ít nhất một ngôn ngữ lập trình, thường là Python, Ruby, hoặc Bash scripting. Kiến thức vững về hệ thống và networking để có thể hiệu quả triển khai và duy trì hệ thống. Kinh nghiệm sử dụng các hệ thống quản lý phiên bản như Git và quy trình phát triển như GitFlow. Kỹ năng thiết lập và duy trì quy trình tự động hóa sử dụng công cụ như Ansible, Puppet, hoặc Chef. Hiểu biết về IaC và sử dụng công cụ như Terraform để quản lý hạ tầng. Kinh nghiệm xây dựng và duy trì các pipeline CI/CD để tự động hóa quy trình phát triển và triển khai. Hiểu biết về giám sát hệ thống và logging để có khả năng phân tích và giải quyết sự cố.',
        expPlus: 'Understanding and implementation of best practices in the DevOps field, including CI/CD, IaC, and automation processes. In-depth training and certifications in DevOps and related technologies.',
        expPlusVN: 'Sự hiểu biết và thực hiện các best practices trong lĩnh vực DevOps, bao gồm quy trình CI/CD, IaC, và tự động hóa. Các chứng chỉ và đào tạo chuyên sâu về DevOps và các công nghệ liên quan.',
        img: require('../../images/rec-devops-engineer.jpg'),
        url: "https://images.pexels.com/photos/113850/pexels-photo-113850.jpeg?auto=compress&cs=tinysrgb&w=1600",
        alt: 'Image',
        benefit: 'Thử việc hưởng 80% lương. Đào tạo nội bộ (nếu có) và ký hợp đồng lao động chính thức sau 06 tháng. Nghỉ phép 12 ngày/năm, Golden Week, Tết dương lịch, các ngày lễ theo lịch đỏ của Nhật, kỷ niệm thành lập công ty. Nghỉ hè 3 ngày tự chọn. Làm việc: 9h-18h từ T2-T6, nghỉ T7 và CN hàng tuần. Thưởng 2 lần/năm (tháng lương thứ 13 và 14). Hỗ trợ thi chứng chỉ quốc tế. Chế độ BHXH, BHYT. Hỗ trợ tiền tầu xe hàng tháng.'
    },
];