// export const allRecruitData = [
//     {
//         displayId: 1,
//         lightText: false,
//         imgStart: true,
//         jobTitle: 'Front-End Developer',
//         location: 'Ha Noi',
//         shortDescription: ['ReactJS', 'JavaScript', 'HTML', 'CSS'],
//         salary: 'Upto 40M',
//         headline: 'FRONTEND-DEV --- Lead Generation specialist for Online Business',
//         description: 'FRONTEND-DEV --- We are looking for a qualified Front-end developer to join our IT team. You will be responsible for building the client-side of our web applications. You should be able to translate our company and customer needs into functional and appealing interactive applications. If you’re interested in creating a user-friendly environment by writing code and moving forward in your career, then this job is for you. We expect you to be a tech-savvy professional, who is curious about new digital technologies and aspires to combine usability with visual design. Ultimately, you should be able to create a functional and attractive digital environment for our company, ensuring great user experience.',
//         experience: ['FRONTEND-DEV --- Proven work experience as a ReactJS developer.', 'Hands on experience with markup languages.', 'Experience with JavaScript, CSS and jQuery.', 'Familiarity with browser testing and debugging. In-depth understanding of the entire web development process (design, development and deployment).'],
//         expPlus: ['FRONTEND-DEV --- Experience with performance optimization, data caching is a plus.', 'Experience working with CDN like Akamai to deliver the best experience (optimization, caching, edge computing…)', 'Good knowledge of end-to-end design language using token.', 'Experience with customer facing roles is a plus.', 'Experience with large-scale e-commerce projects is a plus.', 'Experience with Azure cloud native deployment is a plus.'],
//         img: require('../../images/about.png'),
//         url: "https://images.pexels.com/photos/57007/pexels-photo-57007.jpeg?auto=compress&cs=tinysrgb&w=1600",
//         alt: 'Image',
//         treatment: ['FRONTEND-DEV --- Thử việc hưởng 100% lương', 'Ký hợp đồng lao động chính thức sau 02 tháng thử việc.', 'Nghỉ phép 12 ngày/năm, Golden Week, Tết dương lịch, âm lịch 6 ngày, kỷ niệm thành lập công ty', 'Du lịch hè cùng công ty hoặc nghỉ hè 3 ngày tự chọn.', 'Làm việc: 9h-18h từ T2-T6, nghỉ T7 và CN hàng tuần.', 'Xét tăng lương định kỳ 1 năm/lần, thưởng 2 lần/năm (tháng lương thứ 13 và 14)', 'Hỗ trợ thi chứng chỉ quốc tế.', 'Chế độ BHXH, BHYT, BHTN', 'Môi trường trẻ trung năng động, thoải mái, tạo điều kiện để cá nhân phát triển năng lực nhất có thể.', 'Free trà, cà phê, chỗ gửi xe.'],
//     },
//     {
//         displayId: 2,
//         lightText: false,
//         imgStart: false,
//         jobTitle: 'Back-End Developer',
//         location: 'Tokyo',
//         headline: 'BACKEND-DEV --- Lead Generation specialist for Online Business', 
//         shortDescription: ['Python', 'NodeJS', 'MySQL'],
//         salary: 'Upto 40M',
//         description: 'BACKEND-DEV --- We are looking for a qualified Back-end developer to join our IT team. You will be responsible for building the client-side of our web applications. You should be able to translate our company and customer needs into functional and appealing interactive applications. If you’re interested in creating a user-friendly environment by writing code and moving forward in your career, then this job is for you. We expect you to be a tech-savvy professional, who is curious about new digital technologies and aspires to combine usability with visual design. Ultimately, you should be able to create a functional and attractive digital environment for our company, ensuring great user experience.',
//         experience: ['BACKEND-DEV --- Proven work experience as a Python developer.', 'Hands on experience with markup languages.', 'Experience with Python.', 'Familiarity with browser testing and debugging. In-depth understanding of the entire web development process (design, development and deployment).'],
//         expPlus: ['BACKEND-DEV --- Experience with performance optimization, data caching is a plus.', 'Experience working with CDN like Akamai to deliver the best experience (optimization, caching, edge computing…)', 'Good knowledge of end-to-end design language using token.', 'Experience with customer facing roles is a plus.', 'Experience with large-scale e-commerce projects is a plus.', 'Experience with Azure cloud native deployment is a plus.'],
//         img: require('../../images/about.png'),
//         url: "https://images.pexels.com/photos/785418/pexels-photo-785418.jpeg?auto=compress&cs=tinysrgb&w=1600",
//         alt: 'Image',
//         treatment: ['BACKEND-DEV --- Thử việc hưởng 100% lương', 'Ký hợp đồng lao động chính thức sau 02 tháng thử việc.', 'Nghỉ phép 12 ngày/năm, Golden Week, Tết dương lịch, âm lịch 6 ngày, kỷ niệm thành lập công ty', 'Du lịch hè cùng công ty hoặc nghỉ hè 3 ngày tự chọn.', 'Làm việc: 9h-18h từ T2-T6, nghỉ T7 và CN hàng tuần.', 'Xét tăng lương định kỳ 1 năm/lần, thưởng 2 lần/năm (tháng lương thứ 13 và 14)', 'Hỗ trợ thi chứng chỉ quốc tế.', 'Chế độ BHXH, BHYT, BHTN', 'Môi trường trẻ trung năng động, thoải mái, tạo điều kiện để cá nhân phát triển năng lực nhất có thể.', 'Free trà, cà phê, chỗ gửi xe.'],
//     },
//     {
//         displayId: 3,
//         lightText: false,
//         imgStart: true,
//         jobTitle: 'Cloud Engineer',
//         location: 'Tokyo',
//         headline: 'CLOUD --- Lead Generation specialist for Online Business', 
//         shortDescription: ['AWS', 'Azure', 'Alibaba'],
//         salary: 'Upto 40M',
//         description: 'CLOUD --- We are looking for a qualified CLOUD developer to join our IT team. You will be responsible for building the client-side of our web applications. You should be able to translate our company and customer needs into functional and appealing interactive applications. If you’re interested in creating a user-friendly environment by writing code and moving forward in your career, then this job is for you. We expect you to be a tech-savvy professional, who is curious about new digital technologies and aspires to combine usability with visual design. Ultimately, you should be able to create a functional and attractive digital environment for our company, ensuring great user experience.',
//         experience: ['CLOUD --- Proven work experience as a Cloud Professional.', 'Hands on experience with markup languages.', 'Experience with Python.', 'Familiarity with browser testing and debugging. In-depth understanding of the entire web development process (design, development and deployment).'],
//         expPlus: ['CLOUD --- Experience with performance optimization, data caching is a plus.', 'Experience working with CDN like Akamai to deliver the best experience (optimization, caching, edge computing…)', 'Good knowledge of end-to-end design language using token.', 'Experience with customer facing roles is a plus.', 'Experience with large-scale e-commerce projects is a plus.', 'Experience with Azure cloud native deployment is a plus.'],
//         img: require('../../images/about.png'),
//         url: "https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=1600",
//         alt: 'Image',
//         treatment: ['CLOUD --- Thử việc hưởng 100% lương', 'Ký hợp đồng lao động chính thức sau 02 tháng thử việc.', 'Nghỉ phép 12 ngày/năm, Golden Week, Tết dương lịch, âm lịch 6 ngày, kỷ niệm thành lập công ty', 'Du lịch hè cùng công ty hoặc nghỉ hè 3 ngày tự chọn.', 'Làm việc: 9h-18h từ T2-T6, nghỉ T7 và CN hàng tuần.', 'Xét tăng lương định kỳ 1 năm/lần, thưởng 2 lần/năm (tháng lương thứ 13 và 14)', 'Hỗ trợ thi chứng chỉ quốc tế.', 'Chế độ BHXH, BHYT, BHTN', 'Môi trường trẻ trung năng động, thoải mái, tạo điều kiện để cá nhân phát triển năng lực nhất có thể.', 'Free trà, cà phê, chỗ gửi xe.'],
//     },
//     {
//         displayId: 4,
//         lightText: false,
//         imgStart: false,
//         jobTitle: 'Devops Engineer',
//         location: 'Tokyo',
//         headline: 'DEVOPS --- Lead Generation specialist for Online Business',
//         shortDescription: ['Docker', 'Rancher', 'Kubernetes'],
//         salary: 'Upto 40M',
//         description: 'DEVOPS --- We are looking for a qualified Front-end developer to join our IT team. You will be responsible for building the client-side of our web applications. You should be able to translate our company and customer needs into functional and appealing interactive applications. If you’re interested in creating a user-friendly environment by writing code and moving forward in your career, then this job is for you. We expect you to be a tech-savvy professional, who is curious about new digital technologies and aspires to combine usability with visual design. Ultimately, you should be able to create a functional and attractive digital environment for our company, ensuring great user experience.',
//         experience: ['DEVOPS --- Proven work experience as a Cloud Professional.', 'Hands on experience with markup languages.', 'Experience with Python.', 'Familiarity with browser testing and debugging. In-depth understanding of the entire web development process (design, development and deployment).'],
//         expPlus: ['DEVOPS --- Experience with performance optimization, data caching is a plus.', 'Experience working with CDN like Akamai to deliver the best experience (optimization, caching, edge computing…)', 'Good knowledge of end-to-end design language using token.', 'Experience with customer facing roles is a plus.', 'Experience with large-scale e-commerce projects is a plus.', 'Experience with Azure cloud native deployment is a plus.'],
//         img: require('../../images/about.png'),
//         url: "https://images.pexels.com/photos/113850/pexels-photo-113850.jpeg?auto=compress&cs=tinysrgb&w=1600",
//         alt: 'Image',
//         treatment: ['DEVOPS --- Thử việc hưởng 100% lương', 'Ký hợp đồng lao động chính thức sau 02 tháng thử việc.', 'Nghỉ phép 12 ngày/năm, Golden Week, Tết dương lịch, âm lịch 6 ngày, kỷ niệm thành lập công ty', 'Du lịch hè cùng công ty hoặc nghỉ hè 3 ngày tự chọn.', 'Làm việc: 9h-18h từ T2-T6, nghỉ T7 và CN hàng tuần.', 'Xét tăng lương định kỳ 1 năm/lần, thưởng 2 lần/năm (tháng lương thứ 13 và 14)', 'Hỗ trợ thi chứng chỉ quốc tế.', 'Chế độ BHXH, BHYT, BHTN', 'Môi trường trẻ trung năng động, thoải mái, tạo điều kiện để cá nhân phát triển năng lực nhất có thể.', 'Free trà, cà phê, chỗ gửi xe.'],
//     },
// ];