export const allRecruitData = [
    {
        id: 1,
        lightBg: true,
        imgStart: true,
        lightTopLine: false,
        lightTextDesc: false,
        buttonLabel: 'Details & Apply',
        description: 'React JS. We help business owners increase their revenue. Our team of unique specialist can help you acheive your business goals.',
        headline: 'React JS. Lead Generation specialist for Online Business', 
        lightText: false, 
        topLine: 'Front End Developer',
        primary: false,
        img: require('../../images/dev1.png'),
        alt: 'Image',
        start: ''
    },
    {
        id: 2,
        lightBg: true,
        imgStart: false,
        lightTopLine: false,
        lightTextDesc: false,
        buttonLabel: 'Details & Apply',
        description: 'Python. We help business owners increase their revenue. Our team of unique specialist can help you acheive your business goals.',
        headline: 'Python. Lead Generation specialist for Online Business', 
        lightText: false, 
        topLine: 'Python Developer',
        primary: false,
        img: require('../../images/dev2.png'),
        alt: 'Image',
        start: 'true'
    },
    {
        id: 3,
        lightBg: true,
        imgStart: true,
        lightTopLine: false,
        lightTextDesc: false,
        buttonLabel: 'Details & Apply',
        description: 'AWS Cloud. We help business owners increase their revenue. Our team of unique specialist can help you acheive your business goals.',
        headline: 'AWS Cloud. Lead Generation specialist for Online Business', 
        lightText: false, 
        topLine: 'AWS Cloud Engineer',
        primary: false,
        img: require('../../images/dev3.png'),
        alt: 'Image',
        start: ''
    },
    {
        id: 4,
        lightBg: true,
        imgStart: false,
        lightTopLine: false,
        lightTextDesc: false,
        buttonLabel: 'Details & Apply',
        description: 'DevOps. We help business owners increase their revenue. Our team of unique specialist can help you acheive your business goals.',
        headline: 'DevOps. Lead Generation specialist for Online Business', 
        lightText: false, 
        topLine: 'DevOps Engineer',
        primary: false,
        img: require('../../images/dev1.png'),
        alt: 'Image',
        start: ''
    }
];